### ISSUE TITLE
Support arbitrary size BSONS

### ISSUE THREAD

**Issue by koraa** [mongodb/mongo-tools#37]
Bsondump right now supports BSONs no larger than 16MB; 
instead at least bsondump should support arbitrarily large BSONs.

This will require allocating the buffers based on file size and using 64bit integers at some places where you deal with bson size.

**Comment by gabrielrussell** [comment]
The reason that we don't support BSON documents larger then 16mb is because bson documents larger then 16mb are disallowed by mongod. If your bson file is the result of a dump, and contains large documents, then it's likely corrupt. If you needed to dump larger then 16mb bson documents for some other reason, then you should just fork bsondump and customize it for your special needs.

**Comment by koraa** [comment]
@gabrielrussell BSON is used in projects unrelated to mongodb! In order to accomodate those cases I suggest you either introduce a command line flag or a warning for dealing with BSONs > 16mb, but just not supporting them is rather nasty for any project besides mongodb (or for forward compatibility, where BSONs > 16mb might be supported by mongo itself).

"… should be enough for anyone" usually turns out to be false after at most 10 years.

**Comment by koraa** [comment]
In my specific case it was a debug dump, which I just wanted to convert in order to look at it...
