### ISSUE TITLE
3.1.9 was rereleased

### ISSUE THREAD

**Issue by ryandesign** [mongodb/mongo-tools#43]
3.1.9 was originally released September 25, 2015; I updated the MacPorts project's mongo-tools port to this version on September 27.

The 3.1.9 tag appears to have been recreated on October 2, 2015, with different contents. This [causes MacPorts installations of mongo-tools to now fail](https://trac.macports.org/ticket/49318) because the checksums of the tarball are different.

Was this re-tagging intentional? If so, why was a new version number not assigned instead? You should never change a released tag; they should be consider immutable.

**Comment by gabrielrussell** [comment]
Ryan,

I agree with you that released tags should be considered immutable.

Because most people don't distribute the tools out of the tools repo, but from the mongo repo, we generally consider the tags in the tools repo to be for consumption of the mongo repo, as opposed to the general public.

We generally tag the tools repo in advance of the mongo repo, but in this case we mistakenly tagged the tools repo too early.

We (nearly) never re-tag the mongo repo. Once the tag shows up in the mongo repo, then the same tag in the tools repo is effeminately not going to be rewritten.

That said, if we know that there are consumers of these tools repo tags then we'll just be more careful to do it right.

Gabriel

**Comment by ryandesign** [comment]
Thanks.

Just so I understand, are you saying that the releases tab of this mongo-tools github project is not the correct place to download official releases of mongo-tools? If so, what is the correct place?

**Comment by gabrielrussell** [comment]
No, I was mistaken. That is in fact the correct place to grab the the tools source code releases.

What I said about the tools release not being real until the server release happens still stands. I realize that this is a bit awkward, and we'll talk internally about a better way to do this.

**Comment by mpobrien** [comment]
Closing this one out - @ryandesign we're planning on a new branching/tagging workflow that should eliminate this potential issue for future releases, will keep you posted on that.
