### ISSUE TITLE
mongodump with gzip is not working properly with mongorestore with gzip

### ISSUE THREAD

**Issue by harryssuperman** [mongodb/mongo-tools#65]
Hi guys,

I was exporting data with mongodump with compresion with gzip parameter, but if i try to restore the same collection with the gzip parameter i am only importing the data and not restoring the index of this collection.

What i have, it is after dumping:

collection.bson.gz           collection.metadata.json.gz

Then i run:
 
mongorestore -v -h localhost -d database -c collection --gzip --drop  collection.bson.gz   

Then I expect to have the collection again with the index in database but in the console i read "restoring collection without metadata" even if the file is there. And also the information in the console is not completely right because i read something like "no index to restore" and the filesize 

287.9 MB/59.0 MB  (488.1%)
454.5 MB/59.0 MB  (770.6%)

**Comment by nleite** [comment]
@harryssuperman this type of question are better placed at [mongodb users google groups forum](https://groups.google.com/forum/#!forum/mongodb-user). 
You are experiencing this because you are not importing the **collection.metadata.json.gz** file, which contains the index definition instructions. 
To import both metadata and bson files you need to import the full database 
`mongorestore -d database --gzip --drop --dir=basedir`

**Comment by visemet** [comment]
@harryssuperman, I think you're describing the same issue reported in [TOOLS-1016](https://jira.mongodb.org/browse/TOOLS-1016), which was fixed in version 3.2.2 of the tools. What version of the tools are you using?

**Comment by harryssuperman** [comment]
@visemet Yes exactly i was using this version of the tools
