### ISSUE TITLE
TOOLS-1732 mongoreplay: error: pcap.h: No such file or directory

### ISSUE THREAD

**Issue by sjackman** [mongodb/mongo-tools#86]
`pcap.h` is installed but in an atypical location. How do I specify the location of `pcap.h`?

```
Building mongoreplay...
# github.com/google/gopacket/pcap
vendor/src/github.com/google/gopacket/pcap/pcap.go:19:18: fatal error: pcap.h: No such file or directory
compilation terminated.
```
https://travis-ci.org/Linuxbrew/homebrew-core/builds/191150506#L1867

**Comment by timotheecour** [comment]
https://github.com/Linuxbrew/homebrew-core/pull/1578 seems to fix

**Comment by billybanfield** [comment]
hey @sjackman! 
Thanks for filing an issue against the mongo-tools. Is this issue still occurring? 

Since you said that pcap.h is in an atypical location then you will likely need to specify it using cflags similarly to how you would if compiling a c program. With CGO this is done using the parameter CGO_CFLAGS with the -I flag. This would look like

    go build CGO_CFLAGS="-I/Path/To/Header/Files" -o /path/to/output /path/to/mongoreplay

**Comment by sjackman** [comment]
Hi, Billy. I believe the original PR https://github.com/Linuxbrew/homebrew-core/pull/2941 was resolved. Thanks for your suggestion though.
